/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhom10_qlx;

import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Dell
 */
public class F_Manhinhchinh extends javax.swing.JFrame {

    public F_Manhinhchinh() {
        initComponents();
        imageScale();
    }

    private void imageScale() {
        ImageIcon icon = new ImageIcon(".\\res\\xe.jpg");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(imgBG.getWidth(), imgBG.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleIcon = new ImageIcon(imgScale);
        imgBG.setIcon(scaleIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBanXe = new javax.swing.JButton();
        btnMenuLoaiXe = new javax.swing.JButton();
        btnQuanLyTaiKhoan = new javax.swing.JButton();
        btnQLX = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        imgBG = new javax.swing.JLabel();
        btnDangXuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HỆ THỐNG QUẢN LÝ BÁN XE ÔTÔ");

        btnBanXe.setBackground(new java.awt.Color(102, 102, 102));
        btnBanXe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBanXe.setText("Bán Xe");
        btnBanXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanXeActionPerformed(evt);
            }
        });

        btnMenuLoaiXe.setBackground(new java.awt.Color(102, 102, 102));
        btnMenuLoaiXe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMenuLoaiXe.setText("Quản lý Loại Xe");
        btnMenuLoaiXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuLoaiXeActionPerformed(evt);
            }
        });

        btnQuanLyTaiKhoan.setBackground(new java.awt.Color(102, 102, 102));
        btnQuanLyTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQuanLyTaiKhoan.setLabel("Quản Lý Tài Khoản");
        btnQuanLyTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyTaiKhoanActionPerformed(evt);
            }
        });

        btnQLX.setBackground(new java.awt.Color(102, 102, 102));
        btnQLX.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQLX.setText("Quản Lý Xe");
        btnQLX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLXActionPerformed(evt);
            }
        });

        btnHoaDon.setBackground(new java.awt.Color(102, 102, 102));
        btnHoaDon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHoaDon.setText("Tổng Hợp Hóa Đơn");
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });

        btnDangXuat.setBackground(new java.awt.Color(102, 102, 102));
        btnDangXuat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(btnQLX, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(btnQuanLyTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(btnBanXe, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(btnMenuLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(imgBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(btnQLX, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(btnQuanLyTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnBanXe, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(btnMenuLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1))
            .addComponent(imgBG, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnQuanLyTaiKhoan.getAccessibleContext().setAccessibleName("Quản Lý Tài Khoản");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        F_DangNhap f = new F_DangNhap();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        // TODO add your handling code here:
        F_DanhSachHoaDon fmHD = new F_DanhSachHoaDon();
        fmHD.setVisible(true);
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnMenuLoaiXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuLoaiXeActionPerformed
        // TODO add your handling code here:
        F_LoaiXe fmLoaiXe = new F_LoaiXe();
        fmLoaiXe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuLoaiXeActionPerformed

    private void btnQLXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLXActionPerformed
        // TODO add your handling code here:
        F_QuanlyXe fmQLX = null;
        try {
            fmQLX = new F_QuanlyXe();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(F_Manhinhchinh.class.getName()).log(Level.SEVERE, null, ex);
        }
        fmQLX.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLXActionPerformed

    private void btnBanXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanXeActionPerformed
        // TODO add your handling code here:
        F_BanXe fmBanXe = new F_BanXe();
        fmBanXe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBanXeActionPerformed

    private void btnQuanLyTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyTaiKhoanActionPerformed
        // TODO add your handling code here:
        F_QuanLyTaiKhoan fmQLTK = new F_QuanLyTaiKhoan();
        fmQLTK.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuanLyTaiKhoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Manhinhchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Manhinhchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Manhinhchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Manhinhchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Manhinhchinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanXe;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnMenuLoaiXe;
    private javax.swing.JButton btnQLX;
    private javax.swing.JButton btnQuanLyTaiKhoan;
    private javax.swing.JLabel imgBG;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
